---
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Chi-squared 분포



```{r cars}
set.seed(9)
x <- seq(0,500,by=0.001)
df <- 3
mean.4   <- rep(NA, 1000)     # 결측치 생성 
mean.16  <- rep(NA, 1000)
mean.32  <- rep(NA, 1000)
mean.256 <- rep(NA, 1000)

for(i in 1:1000) {         
  mean.4[i]   <- mean(rchisq(4,df))
  mean.16[i]  <- mean(rchisq(16,df))
  mean.32[i]  <- mean(rchisq(32,df))
  mean.256[i] <- mean(rchisq(256,df))
}

c(mean(mean.4), sd(mean.4))
c(mean(mean.16), sd(mean.16))
c(mean(mean.32), sd(mean.32))
c(mean(mean.256), sd(mean.256))

par(mfrow=c(2,2))
hist(mean.4, prob=T, main = "카이제곱분포 df=3, n= 4",
     col = "cyan")
x1 <- seq(min(mean.4), max(mean.4),length = 1000)
y1 <- dnorm(x1, mean = 3, sd = sqrt(6) / sqrt(4))
lines(x1, y1, lty=2, lwd=2, col="blue")

hist(mean.16, prob=T, main = "카이제곱분포 df=3, n= 16",
     col = "cyan")
x2 <- seq(min(mean.16), max(mean.16),length = 1000)
y2 <- dnorm(x2, mean = 3, sd = sqrt(6) / sqrt(16))
lines(x2, y2, lty=2, lwd=2, col="blue")

hist(mean.32, prob=T, main = "카이제곱분포 df=3, n= 32",
     col = "cyan")
x3 <- seq(min(mean.32), max(mean.32),length = 1000)
y3 <- dnorm(x3, mean = 3, sd = sqrt(6) / sqrt(32))
lines(x3, y3, lty=2, lwd=2, col="blue")

hist(mean.256, prob=T, main = "카이제곱분포 df=3, n= 256",
     col = "cyan")
x4 <- seq(min(mean.32), max(mean.32),length = 1000)
y4 <- dnorm(x4, mean = 3, sd = sqrt(6) / sqrt(256))
lines(x4, y4, lty=2, lwd=2, col="blue")

```


## T- 분포

```{r}
set.seed(100)
x <- seq(-100,100,by=0.001)
df <- 8
mean.10   <- rep(NA, 1000)     # 결측치 생성 
mean.20   <- rep(NA, 1000)
mean.30   <- rep(NA, 1000)
mean.40   <- rep(NA, 1000)

for(i in 1:1000) {         
  mean.10[i]  <- mean(rt(10,df))
  mean.20[i]  <- mean(rt(20,df))
  mean.30[i]  <- mean(rt(30,df))
  mean.40[i]  <- mean(rt(40,df))
}

c(mean(mean.10), sd(mean.10))
c(mean(mean.20), sd(mean.20))
c(mean(mean.30), sd(mean.30))
c(mean(mean.40), sd(mean.40))

par(mfrow=c(2,2))
hist(mean.10, prob=T, main = "T분포 df=8, n= 10",
     col = "cyan")
x1 <- seq(min(mean.10), max(mean.10),length = 1000)
y1 <- dnorm(x1, mean = 0, sd = sqrt(8/6) / sqrt(10))
lines(x1, y1, lty=2, lwd=2, col="blue")

hist(mean.20, prob=T, main = "T분포 df=8, n= 20",
     col = "cyan")
x2 <- seq(min(mean.20), max(mean.20),length = 1000)
y2 <- dnorm(x2, mean = 0, sd = sqrt(8/6) / sqrt(20))
lines(x2, y2, lty=2, lwd=2, col="blue")


hist(mean.30, prob=T, main = "T분포 df=8, n= 30",
     col = "cyan")
x3 <- seq(min(mean.30), max(mean.30),length = 1000)
y3 <- dnorm(x3, mean = 0, sd = sqrt(8/6) / sqrt(30))
lines(x3, y3, lty=2, lwd=2, col="blue")

hist(mean.40, prob=T, main = "T분포 df=8, n= 40",
     col = "cyan")
x4 <- seq(min(mean.40), max(mean.40),length = 1000)
y4 <- dnorm(x4, mean = 0, sd = sqrt(8/6) / sqrt(40))
lines(x4, y4, lty=2, lwd=2, col="blue")





```



## F- 분포


```{r}
set.seed(100)
x <- seq(0,1500,by=0.001)
df1 <- 5
df2 <- 10
mean.50   <- rep(NA, 1000)     # 결측치 생성 
mean.60   <- rep(NA, 1000)
mean.70   <- rep(NA, 1000)
mean.80   <- rep(NA, 1000)

for(i in 1:1000) {         
  mean.50[i]  <- mean(rf(50,df1,df2))
  mean.60[i]  <- mean(rf(60,df1,df2))
  mean.70[i]  <- mean(rf(70,df1,df2))
  mean.80[i]  <- mean(rf(80,df1,df2))
}

c(mean(mean.50), sd(mean.50))
c(mean(mean.60), sd(mean.60))
c(mean(mean.70), sd(mean.70))
c(mean(mean.80), sd(mean.80))


par(mfrow=c(2,2))

hist(mean.50, prob=T, main = "F분포 df=5,10, n= 50",
     col = "cyan")
x1 <- seq(min(mean.50), max(mean.50),length = 1000)
y1 <- dnorm(x1, mean = 10/8, sd = (2 *(10^2) * (15+10-2)) / ((5 * (10-2)^2) * (10-4)) / sqrt(50))
lines(x1, y1, lty=2, lwd=2, col="blue")


hist(mean.60, prob=T, main = "F분포 df=5,10, n= 60",
     col = "cyan")
x2 <- seq(min(mean.60), max(mean.60),length = 1000)
y2 <- dnorm(x2, mean = 10/8, sd = (2 *(10^2) * (15+10-2)) / ((5 * (10-2)^2) * (10-4)) / sqrt(60))
lines(x2, y2, lty=2, lwd=2, col="blue")


hist(mean.70, prob=T, main = "F분포 df=5,10, n= 70",
     col = "cyan")
x3 <- seq(min(mean.70), max(mean.70),length = 1000)
y3 <- dnorm(x3, mean = 10/8, sd = (2 *(10^2) * (15+10-2)) / ((5 * (10-2)^2) * (10-4)) / sqrt(70))
lines(x3, y3, lty=2, lwd=2, col="blue")


hist(mean.80, prob=T, main = "F분포 df=5,10, n= 80",
     col = "cyan")
x4 <- seq(min(mean.80), max(mean.80),length = 1000)
y4 <- dnorm(x4, mean = 10/8, sd = (2 *(10^2) * (15+10-2)) / ((5 * (10-2)^2) * (10-4)) / sqrt(80))
lines(x4, y4, lty=2, lwd=2, col="blue")


```





Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
